# Generated by Django 4.2.7 on 2023-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='pages',
            new_name='ano_lancamento',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publishing_company',
            new_name='editora',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='release_year',
            new_name='total_de_paginas',
        ),
    ]
